### ISSUE TITLE
Question: Possible to pull a specific cell (row + col) with this plugin?

### ISSUE THREAD

**Issue by henry74** [sondrele/gatsby-source-google-spreadsheet#1]
I'm looking to create a dashboard and I'd like to just pull a few specific cells (instead of rows) from a Google sheet using GraphQL. Is it possible with this plugin and if so, can you provide a quick example?

**Comment by sondrele** [comment]
Hi! This is not possible as of now, this plugin pulls all sheets and their rows and columns by default, so I haven't implemented any options to support features like this.

However, since it's based on the V4 of the Google Sheets API, it should be fairly easy to configure the options to only source cells based on the [A1 notation](https://developers.google.com/sheets/api/guides/concepts#a1_notation), instead of the default behavior.

I don't have time to implement this right now, but I'll be happy to accept a PR for it, otherwise I might have some spare time during the next few weeks to look at it :)

**Comment by henry74** [comment]
No worries.  I've created a [graphql wrapper for google sheets](https://github.com/henry74/googlesheets-graphql-server) based on v4 and leveraging A1 notation.
